version: '3.5'

services:
    app:
        build: ./docker/images/php81
        volumes:
            - ./application:/var/www/html
#            - ./docker/images/cron/files:/var/spool/cron/crontabs/
        ports:
            - "8085:8000"
        links:
            - postgresql
#            - supervisor
        working_dir: /var/www/html
    postgresql:
        image: postgres:14.1-alpine
        ports:
            - "5422:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pQLkm8NOk123OBox
            POSTGRES_DB: emax
        volumes:
            - ./docker/images/postgres/files/postgresql.conf:/etc/postgresql.conf
        command: [ "postgres", "-c", "config_file=/etc/postgresql.conf" ]
        restart: always
#    supervisor:
#        build: ./docker/images/supervisor
#        working_dir: /var/www/html
#        restart: unless-stopped
#        volumes:
#            - ./application:/var/www/html
#            - ./docker/images/supervisor/files:/etc/supervisor/conf.d/
#        ports:
#            - "8003:8008"


